POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/601c0f08-48a9-45e2-887f-31a4386a090f
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/b16612c4-19e6-4452-afff-375156d15614